### ISSUE TITLE
query prints "No results to return", can't turn off

### ISSUE THREAD

**Issue by cossio** [biothings/mygene.py#2] opened 2017-11-22 01:52 UTC
I need to do some text processing on the output of `query`. I set `fetch_all = True` because the query is large. But then it prints two messages that make parsing more difficult:

```
Fetching 30 genes(s) . . .
No results to return
```

I discoverd the flag `verbose` and set it to False, but it still prints `No results to return`. How can I turn this off?

**Comment by namespacestd0** [comment] 2019-03-06 18:16
Fixed in [546f2e30](https://github.com/biothings/biothings_client.py/commit/546f2e303e1a59d74995228c748e50074babf1c6) Caused by inproper detection of the end of result, thus producing an "error" type message, bypassing verbosity setting.

**Closed by namespacestd0** 2019-03-06 18:16 UTC
