### ISSUE TITLE
TypeError on importing mygene

### ISSUE THREAD

**Issue by ag1805x** [biothings/mygene.py#21] opened 2022-09-01 07:03 UTC
While calling for `mygene` in jupyter notebook, I am getting the following error:

```
import mygene
TypeError: Invalid first argument to `register()`. ForwardRef('CachedResponse') is not a class.
```

This is a new issue since I had previously the package on the same notebook until December 2021 successfully. It is only now when I tried to rerun, I encountered the error.

**Comment by newgene** [comment] 2022-09-01 15:25
@ag1805x can you provide the full traceback error and other relevant information (package and Python version, OS etc)? Or give it a try directly in a Python console to see if you have the same error?

This error msg does not look like coming from the `mygene` package itself, but could be from its dependencies.

**Comment by newgene** [comment] 2023-01-06 00:08
close this issue now as we cannot reproduce the described error.

**Closed as completed by newgene** 2023-01-06 00:08 UTC
